LVLgroupApp/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using Azure;
using Core.Constants;
using Core.Entities.Business;
using Core.Entities.Identity;
using Core.Entities.Mail;
using Core.Entities.Select2;
using Core.Enums;
using Core.Features.Charts.CountQueries.CountAllClaimsCached;
using Core.Features.Claims.Queries.GetAllCached;
using Core.Features.Gruposlojas.Queries.GetById;
using Core.Features.Lojas.Queries.GetAllCached;
using Core.Features.Lojas.Queries.GetById;
using Core.Interfaces.Shared;
using Infrastructure.Data.DbContext;
using LVLgroupApp.Abstractions;
using LVLgroupApp.Areas.Admin.Models;
using LVLgroupApp.Areas.Business.Controllers.Empresa;
using LVLgroupApp.Areas.Business.Controllers.Grupoloja;
using LVLgroupApp.Areas.Business.Controllers.Loja;
using LVLgroupApp.Areas.Claim.Models.Claim;
using LVLgroupApp.Areas.Notification.Models.Notification;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace LVLgroupApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : BaseController<UserController>
    {

        //---------------------------------------------------------------------------------------------------


        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly IStringLocalizer<UserController> _localizer;

        private readonly IMailService _emailSender;

        private readonly DateTime _endDate;


        //---------------------------------------------------------------------------------------------------


        public UserController(UserManager<ApplicationUser> userManager, 
                              SignInManager<ApplicationUser> signInManager, 
                              RoleManager<IdentityRole> roleManager, 
                              IStringLocalizer<UserController> localizer,
                              IMailService emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _localizer = localizer;
            _emailSender = emailSender;

            _endDate = new DateTime(2222, 06, 06);
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Users.View)]
        public IActionResult Index()
        {
            return View();
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Users.View)]
        public async Task<IActionResult> LoadAll()
        {
            try
            {
                var users = _context.Users.ToList();
                var allUsers = new List<UserViewModel>();

                foreach(ApplicationUser user in users)
                {
                    _logger.LogInformation(_sessionId + " | " + _sessionName + " | User Contoller - LoadAll - Vai ler os roles de: " + user.Email);
                    var roles = await _userManager.GetRolesAsync(user);
                    var userRoles = roles.ToList();

                    var uvm = new UserViewModel()
                    {
                        Id = user.Id,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        UserName = user.UserName,
                        RoleName = roles.Count > 0 ? roles[0] : string.Empty,
                        Email = user.Email,
                        EmailConfirmed = user.EmailConfirmed,
                        ProfilePicture = user.ProfilePicture,
                        IsActive = user.IsActive,
                    };

                    if (user.EmpresaId != null)
                    {
                        var emp = await EmpresaController.GetEmpresaAsync((int)user.EmpresaId, _mapper, _mediator);
                        uvm.NomeEmpresa = emp.Nome;
                    }
                    if (user.GrupolojaId != null)
                    {
                        uvm.NomeGrupoloja = await GrupolojaController.GetGrupolojaNomeAsync((int)user.GrupolojaId, _mapper, _mediator);
                    }
                    if (user.LojaId != null)
                    {
                        uvm.NomeLoja = await LojaController.GetLojaNomeAsync((int)user.LojaId, _mapper, _mediator);
                    }

                    allUsers.Add(uvm);
                }
                return PartialView("_ViewAll", allUsers);
            }
            catch (Exception ex)
            {
                _logger.LogError(_sessionId + " | " + _sessionName + " | User Contoller - LoadAll - Exception vai sair e retornar Error: " + ex.Message);
                return new ObjectResult(new { status = "error" });
            }
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Users.Create)]
        public async Task<IActionResult> OnGetCreate()
        {
            var model = new UserViewModel();
            model.EmailConfirmed = true;
            return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", model) });
        }


        //---------------------------------------------------------------------------------------------------


        [HttpPost]
        [Authorize(Policy = Permissions.Users.Create)]
        public async Task<IActionResult> OnPostCreate(UserViewModel userModel)
        {
            if (ModelState.IsValid)
            {
                MailAddress address = new MailAddress(userModel.Email);
                string userName = address.User;
                var user = new ApplicationUser
                {
                    UserName = userName,
                    Email = userModel.Email,
                    FirstName = userModel.FirstName,
                    LastName = userModel.LastName,
                    EmailConfirmed = userModel.EmailConfirmed
                };
                
                var result = await _userManager.CreateAsync(user, userModel.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, Roles.Colaborador.ToString());
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);

                    if (!userModel.EmailConfirmed)
                    {
                        // ------ send email --------
                        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                        var callbackUrl = Url.Page(
                            "/Account/ConfirmEmail",
                            pageHandler: null,
                            values: new { area = "Identity", userId = user.Id, code = code, returnUrl = Url.Content("~/") },
                            protocol: Request.Scheme);
                        var mailRequest = new MailRequest
                        {
                            Body = $"{_localizer["Please confirm your account by"]} <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>{_localizer["clicking here"]}</a>.",
                            ToEmail = userModel.Email,
                            Subject = _localizer["Confirm Registration"]
                        };
                        await _emailSender.SendAsync(mailRequest);
                    }

                    var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                    var allUsers = await _userManager.Users.ToListAsync();
                    var users = _mapper.Map<IEnumerable<UserViewModel>>(allUsers);
                    var htmlData = await _viewRenderer.RenderViewToStringAsync("_ViewAll", users);
                    _notify.Success($"{_localizer["Foi criada uma conta para "]} {user.Email}.");
                    return new JsonResult(new { isValid = true, html = htmlData });
                }
                foreach (var error in result.Errors)
                {
                    _notify.Error(error.Description);
                }
                var html = await _viewRenderer.RenderViewToStringAsync("_Create", userModel);
                return new JsonResult(new { isValid = false, html = html });
            }
            else
            {
                var html = await _viewRenderer.RenderViewToStringAsync("_Create", userModel);
                return new JsonResult(new { isValid = false, html = html });
            }
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Users.Edit)]
        public async Task<IActionResult> OnGetEdit(string userId = "")
        {
            if (userId == null || userId == "")
            {
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Edit", new UserViewModel()) });
            }
            var model = new UserViewModel();
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Edit", new UserViewModel()) });
            }
            model.NomeEmpresa = string.Empty;
            model.LojaId = 0;
            if (user.LojaId != null)
            {

LVLgroupApp/Areas/Admin/Controllers/UserRoleController.cs
using Core.Constants;
using Core.Enums;
using Core.Entities.Identity;
using Infrastructure.Data.Seeds;
using LVLgroupApp.Abstractions;
using LVLgroupApp.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace LVLgroupApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserRoleController : BaseController<UserRoleController>
    {

        //---------------------------------------------------------------------------------------------------


        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly IStringLocalizer<UserRoleController> _localizer;


        //---------------------------------------------------------------------------------------------------


        public UserRoleController(UserManager<ApplicationUser> userManager, 
                                  SignInManager<ApplicationUser> signInManager, 
                                  RoleManager<IdentityRole> roleManager, 
                                  IStringLocalizer<UserRoleController> localizer)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _localizer = localizer;
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Users.Edit)]
        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            ViewData["Title"] = $"{user.FirstName} {user.LastName} - {_localizer["Funções!"]}";
            ViewData["Caption"] = $"{_localizer["Gestão de funções para"]} {user.Email}.";
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                viewModel.Add(userRolesViewModel);
            }

            IComparer<UserRolesViewModel> comparer = new RoleSorting();
            viewModel.Sort(comparer);

            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };

            return View(model);
        }


        //---------------------------------------------------------------------------------------------------


        [HttpPost]
        [Authorize(Policy = Permissions.Users.Edit)]
        public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));

            user.EmpresaId = null;
            user.GrupolojaId = null;
            user.LojaId = null;
            user.Local = string.Empty;
            await _userManager.UpdateAsync(user);
            
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            await DefaultSuperAdminUser.SeedAsync(_userManager, _roleManager);
            _notify.Success($"{_localizer["Foram atualizadas as funções do utilizador"]} {user.Email}");
            return RedirectToAction("Index", new { userId = id });
        }


        //---------------------------------------------------------------------------------------------------

    }


    //---------------------------------------------------------------------------------------------------


    public class RoleSorting : IComparer<UserRolesViewModel>
    {
        public int Compare(UserRolesViewModel x, UserRolesViewModel y)
        {
            if (x.RoleName == Roles.Basic.ToString()) return -1;
            if (x.RoleName == Roles.SuperAdmin.ToString()) return 1;

            if (x.RoleName == Roles.Colaborador.ToString() && y.RoleName == Roles.Basic.ToString()) return 1;
            if (x.RoleName == Roles.Colaborador.ToString()) return -1;

            if (x.RoleName == Roles.GerenteLoja.ToString() && (y.RoleName == Roles.Basic.ToString() || y.RoleName == Roles.Colaborador.ToString())) return 1;
            if (x.RoleName == Roles.GerenteLoja.ToString()) return -1;

            if (x.RoleName == Roles.Revisor.ToString() && (y.RoleName == Roles.Basic.ToString() || y.RoleName == Roles.Colaborador.ToString() || y.RoleName == Roles.GerenteLoja.ToString())) return 1;
            if (x.RoleName == Roles.Revisor.ToString()) return -1;

            if (x.RoleName == Roles.Supervisor.ToString() && (y.RoleName == Roles.Basic.ToString() || y.RoleName == Roles.Colaborador.ToString() || y.RoleName == Roles.GerenteLoja.ToString() || y.RoleName == Roles.Revisor.ToString())) return 1;
            if (x.RoleName == Roles.Supervisor.ToString()) return -1;

            if (x.RoleName == Roles.Admin.ToString() && (y.RoleName == Roles.Basic.ToString() || y.RoleName == Roles.Colaborador.ToString() || y.RoleName == Roles.GerenteLoja.ToString() || y.RoleName == Roles.Revisor.ToString() || y.RoleName == Roles.Supervisor.ToString())) return 1;
            if (x.RoleName == Roles.Admin.ToString()) return -1;

            return 0;
        }
    }


    //---------------------------------------------------------------------------------------------------

}

LVLgroupApp/Areas/Admin/Views/User/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = localizer["Utilizadores"];
    ViewData["Caption"] = localizer["Gestão de utilizadores"];
}
<div class="card">
    <div class="col-sm-12" style="padding:20px">
        <a onclick="jQueryModalGet('/admin/user/OnGetCreate','Create User', event, 'modal-lg')" class="btn btn-success mb-3">
            <i class="fa fa-plus-square"></i> @localizer["Criar"]
        </a>
        <a id="reload" class="btn btn-primary text-white mb-3">
            <i class="fa fas fa-bolt"></i> @localizer["Recarregar"]
        </a>
    </div>
    <div id="viewAll" class="card-body table-responsive">
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
        function loadData() {
            $.busyLoadSetup({ fontawesome: "fa fa-spinner fa-spin fa-3x fa-fw" });
            $.busyLoadFull("show");
            $('#viewAll').load('/admin/user/LoadAll');
        }
    </script>
}

LVLgroupApp/Areas/Admin/Views/User/_ViewAll.cshtml
@using LVLgroupApp.Areas.Admin.Models
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@model IEnumerable<UserViewModel>

<table id="userTable" class="table table-striped dt-responsive nowrap display hover" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>
                @localizer["Id"]
            </th>
            <th>
                @localizer["Utilizador"]
            </th>
            <th>
                @localizer["E-mail"]
            </th>
            <th>
                @localizer["Status"]
            </th>
            <th>
                @localizer["Empresa"]
            </th>
            <th>
                @localizer["Grupoloja"]
            </th>
            <th>
                @localizer["Loja"]
            </th>
            <th style="width:10%">
                @localizer["Ações"]
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    @user.Id
                </td>
                <td>
                    <div class="row">
                        @if (@user.ProfilePicture != null && user.ProfilePicture.Length > 0)
                        {
                            <div class="col-sm" style=" max-width: 80px;margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 60px;width:60px;object-fit: cover;" src="data:image/*;base64,@(Convert.ToBase64String(@user.ProfilePicture))">
                            </div>
                        }
                        else
                        {
                            <div class="col-sm" style="max-width:80px; margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 60px;width:60px;object-fit: cover;" src="~/images/default-user.png">
                            </div>
                        }
                        <div class="col-sm">
                            <span>@user.FirstName @user.LastName</span>
                            <br>
                            <small>
                                @user.Id
                            </small>
                        </div>
                    </div>
                </td>
                <td>
                    <span>@user.Email</span>
                    <br>
                    <small>
                        @if (user.EmailConfirmed)
                        {
                            <span class="badge text-bg-success">@localizer["E-mail confirmado"]</span>
                        }
                        else
                        {
                            <span class="badge text-bg-danger">@localizer["E-mail não confirmado"]</span>
                        }
                    </small>
                </td>
                <td>
                    @if (user.IsActive)
                    {
                        <span class="badge text-bg-success">@localizer["Ativo"]</span>
                    }
                    else
                    {
                        <span class="badge text-bg-danger">@localizer["Desativado"]</span>
                    }
                    <br/>
                    <span class="badge text-bg-info mt-2">@user.RoleName</span>
                </td>
                <td>
                    @user.NomeEmpresa
                </td>
                <td>
                    @user.NomeGrupoloja
                </td>
                <td>
                    @user.NomeLoja
                </td>
                <td>
                    <div class="btn-group dropend">
                        <button id="dropdown_@user.Id" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @localizer["Ação"] <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-table shadow animated--grow-in" aria-labelledby="dropdown_@user.Id">
                            <li>
                                <a style='margin-right:16px' asp-area="Identity" asp-page="/Profile" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fas fa-cogs"></i>&nbsp; @localizer["Defenições"]
                                </a>
                            </li>
                            <li>
                                <a style='margin-right:16px' asp-area="Identity" asp-page="/Account/Manage/Index" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fas fa-user"></i>&nbsp; @localizer["Perfil"]
                                </a>
                            </li>
                            <li>
                                <a style='margin-right:16px' asp-controller="UserRole" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fas fa-wrench"></i>&nbsp; @localizer["Gestão de funções"]
                                </a>
                            </li>
                            <li>
                                <a style='margin-right:16px' asp-area="Identity" asp-page="/Account/AuditLog" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fas fa-list"></i>&nbsp; @localizer["Logs atividade"]
                                </a>
                            </li>
                            <li>
                                <form id="form_delete_@user.Id" asp-controller="User" method="post" asp-action="OnPostDelete" asp-route-id="@user.Id" onsubmit="return jQueryModalDelete(this, event, '@localizer["Tem a certeza que pretende remover este utilizador?"]')" class="d-inline">
                                    <a href="javascript:$('#form_delete_@user.Id').submit();" class="dropdown-item"><i class="fas fa-trash-alt"></i> @localizer["Remover"]</a>
                                </form>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>



<script>

    $(document).ajaxStop(function () {
        $.busyLoadFull("hide");
    });

    $(document).ready(function () {

        var logo = getLVLlogo('logo-lvl-dark.png');

        var options = {
            isEnabled: true,
            saveState: false
        };

        var languagePath = '@Url.Content("~/lib/datatables/localizer/")';
        var languageFile = '@localizer["Portuguese.json"]';
        var _language = languagePath + languageFile;

        var table = $("#userTable").DataTable({
            dom: "<'row'<'col-sm-12 col-md-4'B><'col-sm-12 col-md-4 mt-1'l><'col-sm-12 col-md-4 mt-1'f>>" +
                 "<'row'<'col-sm-12't>>" +
                 "<'row'<'col-sm-12 col-md-5 mt-3'i><'col-sm-12 col-md-7 mt-3'p>>",
            stateSave: true,
            //scrollX: true,
            //scrollY: true,
            responsive: false,
            fixedHeader: {
                header: true,
                headerOffset: $('#navigationBar').height()
            },
            language: {
                url: _language
            },
            lengthMenu: [
                [20, 50, 100, 500, 1000, -1],
                [20, 50, 100, 500, 1000, '@localizer["Todos"]'],
            ],
            buttons: [
                {
                    extend: 'copy',
                    text: '<i class="fas fa-copy"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de utilizadores"]'
                },
                {
                    extend: 'pdf',
                    text: '<i class="fas fa-file-pdf"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de utilizadores"]',
                    customize: function (doc) {
                        doc.content.splice(1, 0, {
                            margin: [0, 0, 0, 12],
                            alignment: 'center',
                            image: 'data: image/*;base64,' + logo,
                            fit: [100, 100]
                        });
                    }
                },
                {
                    extend: 'excel',
                    text: '<i class="fas fa-file-excel"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de utilizadores"]'
                },
                {
                    extend: 'print',
                    text: '<i class="fas fa-print"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de utilizadores"]'
                },
                {
                    extend: 'colvis',
                    text: '<i class="fas fa-eye-slash"></i>',
                }
            ],
            order: [[0, "desc"]],
            columnDefs: [
                { visible: false, targets: [0] }
            ]
        });

        $('#userTable').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
            $('.dataTables_scrollHead').addClass('dropdown-visible'); 
        })
        .on('hide.bs.dropdown', function () {
            $('.dataTables_scrollBody').removeClass('dropdown-visible');
            $('.dataTables_scrollHead').removeClass('dropdown-visible');
        });

        $('#userTable tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            } else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });

        $('#userTable tbody').on('dblclick', 'tr', function () {
            $(this).addClass('selected');
            var data = table.row(this).data();
            window.location.href = '/Identity/Profile?userId=' + data[0];
        });

        function getLVLlogo(logoName) {

            let _logoName = logoName;
            let _url = "/Claim/Foto/GetLVLlogo?logoName=_logoName";
            let formData = new FormData();
            formData.append("logoName", _logoName);

            $.ajax(
                {
                    type: "POST",
                    url: _url,
                    processData: false,
                    contentType: false,
                    data: formData,
                    dataType: 'json',
                    success: function (data) {
                        if (data.status == "success") {
                            logo = data.logoBase64;
                            //alert(logo);
                        }
                    },
                    error: function () {
                        alert("getLVLlogo: Error occurs");
                    }
                }
            );

        };

    });

</script>