LVLgroupApp/Areas/Artigo/Models/Gender/GenderViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LVLgroupApp.Areas.Artigo.Models.Gender
{
    public class GenderViewModel
    {

        //---------------------------------------------------------------------------------------------------


        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        public string TamanhosNum { get; set; }

        [Required]
        public string TamanhosAlf { get; set; }


        //---------------------------------------------------------------------------------------------------

    }
}

LVLgroupApp/Areas/Artigo/Controllers/Gender/GenderController.cs
using AutoMapper;
using Core.Constants;
using Core.Entities.Select2;
using Core.Features.Genders.Commands.Create;
using Core.Features.Genders.Commands.Delete;
using Core.Features.Genders.Commands.Update;
using Core.Features.Genders.Queries.GetAllCached;
using Core.Features.Genders.Queries.GetById;
using LVLgroupApp.Abstractions;
using LVLgroupApp.Areas.Artigo.Models.Gender;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LVLgroupApp.Areas.Artigo.Controllers.Gender
{
    [Area("Artigo")]
    [Authorize]
    public class GenderController : BaseController<GenderController>
    {

        //---------------------------------------------------------------------------------------------------


        private readonly IStringLocalizer<GenderController> _localizer;


        //---------------------------------------------------------------------------------------------------


        public GenderController(IStringLocalizer<GenderController> localizer)
        {
            _localizer = localizer;
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Genders.View)]
        public IActionResult Index()
        {
            var model = new GenderViewModel();
            return View(model);
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Genders.View)]
        public async Task<IActionResult> LoadAll()
        {
            var response = await _mediator.Send(new GetAllGendersCachedQuery());
            if (response.Succeeded)
            {
                var viewModel = _mapper.Map<List<GenderViewModel>>(response.Data);
                return PartialView("_ViewAll", viewModel);
            }
            return null;
        }


        //---------------------------------------------------------------------------------------------------


        [Authorize(Policy = Permissions.Genders.Create)]
        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0)
        {
            if (id == 0) // Criar novo Gender
            {
                var genderViewModel = new GenderViewModel();
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", genderViewModel) });
            }
            else // Editar Gender
            {
                var response = await _mediator.Send(new GetGenderByIdQuery() { Id = id });
                var genderViewModel = _mapper.Map<GenderViewModel>(response.Data);
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", genderViewModel) });
            }
        }


        //---------------------------------------------------------------------------------------------------


        [HttpPost]
        [Authorize(Policy = Permissions.Genders.Create)]
        public async Task<JsonResult> OnPostCreateOrEdit(int id, GenderViewModel gender)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    //create new Gender
                    var createGenderCommand = _mapper.Map<CreateGenderCommand>(gender);
                    var result = await _mediator.Send(createGenderCommand);
                    if (result.Succeeded)
                    {
                        id = result.Data;
                        _notify.Success($"{_localizer["Género com ID"]} {result.Data} {_localizer[" criado."]}");
                    }
                    else _notify.Error(result.Message);
                }
                else
                {
                    //update Gender
                    var updateGenderCommand = _mapper.Map<UpdateGenderCommand>(gender);
                    var result = await _mediator.Send(updateGenderCommand);
                    if (result.Succeeded) _notify.Information($"{_localizer["Género com ID"]} {result.Data} {_localizer[" atualizado."]}");
                }

                // return _ViewAll

                var response = await _mediator.Send(new GetAllGendersCachedQuery());
                if (response.Succeeded)
                {
                    var viewModel = _mapper.Map<List<GenderViewModel>>(response.Data);
                    var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                    return new JsonResult(new { isValid = true, html = html });
                }
                else
                {
                    _notify.Error(response.Message);
                    return null;
                }
            }
            else
            {
                var html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", gender);
                return new JsonResult(new { isValid = false, html = html });
            }
        }


        //---------------------------------------------------------------------------------------------------


        [HttpPost]
        [Authorize(Policy = Permissions.Genders.Delete)]
        public async Task<JsonResult> OnPostDelete(int id)
        {
            var deleteCommand = await _mediator.Send(new DeleteGenderCommand { Id = id });
            if (deleteCommand.Succeeded)
            {
                _notify.Information($"{_localizer["Género com ID"]} {id} {_localizer[" removido."]}");
                var response = await _mediator.Send(new GetAllGendersCachedQuery());
                if (response.Succeeded)
                {
                    var viewModel = _mapper.Map<List<GenderViewModel>>(response.Data);
                    var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                    return new JsonResult(new { isValid = true, html = html });
                }
                else
                {
                    _notify.Error(response.Message);
                    return null;
                }
            }
            else
            {
                _notify.Error(deleteCommand.Message);
                return null;
            }
        }


        //---------------------------------------------------------------------------------------------------


        public async Task<IActionResult> OnGetListAllGenders(string term)
        {
            var gendersResponse = await _mediator.Send(new GetAllGendersCachedQuery());
            var gendersViewModel = _mapper.Map<List<GenderViewModel>>(gendersResponse.Data);
            List<Select2Item> data = new List<Select2Item>();

            data.Add(new Select2Item
            {
                id = 0,
                text = _localizer["Todos os genders"],
                textColor = "",
                backgroundColor = ""
                //selected = (item.Id == selectedId)
            });

            if (!string.IsNullOrEmpty(term))
            {
                var search = gendersViewModel.Where(g => g.Nome.Contains(term, StringComparison.OrdinalIgnoreCase)).ToList().AsReadOnly();
                foreach (var item in search)
                {
                    data.Add(new Select2Item
                    {
                        id = item.Id,
                        text = item.Nome == null ? "" : item.Nome
                        //selected = (item.Id == selectedId)
                    });
                }
            }
            else
            {
                foreach (var item in gendersViewModel)
                {
                    data.Add(new Select2Item
                    {
                        id = item.Id,
                        text = item.Nome == null ? "" : item.Nome
                        //selected = (item.Id == selectedId)
                    });
                }
            };

            return Ok(data);
        }


        //---------------------------------------------------------------------------------------------------


        public async Task<JsonResult> LoadGenders()
        {

            var gendersResponse = await _mediator.Send(new GetAllGendersCachedQuery());

            if (gendersResponse.Succeeded)
            {
                var genderViewModel = _mapper.Map<List<GenderViewModel>>(gendersResponse.Data);
                var genders = new SelectList(genderViewModel, nameof(GenderViewModel.Id), nameof(GenderViewModel.Nome), null, null);

                var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(new { gendersList = genders });
                return Json(jsonString);
            }
            return null;
        }


        //---------------------------------------------------------------------------------------------------


        public static async Task<GenderViewModel> GetGenderViewModelAsync(int genderId, IMapper mapper, IMediator mediator)
        {
            var genderResponse = await mediator.Send(new GetGenderByIdQuery() { Id = genderId});
            return mapper.Map<GenderViewModel>(genderResponse.Data);
        }


        //---------------------------------------------------------------------------------------------------


        public static async Task<SelectList> GetSelectListAllGendersAsync(int selectedId, IMapper mapper, IMediator mediator)
        {
            var gendersResponse = await mediator.Send(new GetAllGendersCachedQuery());
            var gendersViewModel = mapper.Map<List<GenderViewModel>>(gendersResponse.Data);
            return new SelectList(gendersViewModel, nameof(GenderViewModel.Id), nameof(GenderViewModel.Nome), selectedId, null);
        }


        //---------------------------------------------------------------------------------------------------

    }
}

LVLgroupApp/Areas/Artigo/Views/Gender/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = localizer["Géneros"];
    ViewData["Caption"] = localizer["Configure aqui os tamanhos por género."];
}
@using Core.Constants
@using LVLgroupApp.Areas.Artigo.Models.Gender
@model GenderViewModel

<div class="card">
    <div class="col-sm-12" style="padding:20px">
        @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Create)).Result.Succeeded)
        {
            <a onclick="jQueryModalGet('/Artigo/gender/OnGetCreateOrEdit','@localizer["Criar género"]', event, 'modal-xl')" class="btn btn-success mb-3">
                <i class="fa fa-plus-square"></i> @localizer["Criar"]
            </a>
        }

        <a id="reload" class="btn btn-primary text-white mb-3">
            <i class="fa fas fa-bolt"></i>
            @localizer["Recarregar"]
        </a>
    </div>
    <div id="viewAll" class="card-body table-responsive">
    </div>
</div>


@section Scripts
{
    <script>

        function loadData() {
            $('#viewAll').load('/artigo/gender/LoadAll');
        }

        $(document).ready(function () {
            $("#genderTable").DataTable();
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
    </script>
}

LVLgroupApp/Areas/Artigo/Views/Gender/_CreateOrEdit.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@using Core.Constants
@using LVLgroupApp.Areas.Artigo.Models.Gender
@model GenderViewModel

<form id="create-form" method="post" asp-area="Artigo" asp-controller="Gender" asp-action="OnPostCreateOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this, event, false);" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div class="row pb-3">
                <div class="col-md-12">
                    <div class="form-floating mb-3">
                        <input id="Nome" name="Nome" asp-for="@Model.Nome" type="text" class="form-control" placeholder="name@example.com">
                        <label class="col-form-label" for="Nome">@localizer["Nome"]</label>
                        <small><span asp-validation-for="@Model.Nome" class="text-danger"></span></small>
                    </div>
                </div>
            </div>
            <div class="row pb-3">
                <div class="col-md-12">
                    <div class="form-floating mb-3">
                        <input id="TamanhosAlf" name="TamanhosAlf" asp-for="@Model.TamanhosAlf" type="text" class="form-control" placeholder="name@example.com">
                        <label class="col-form-label" for="TamanhosAlf">@localizer["Tamanhos alfanuméricos"]</label>
                        <small><span asp-validation-for="@Model.TamanhosAlf" class="text-danger"></span></small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-floating mb-3">
                <textarea id="TamanhosNum" name="TamanhosNum" asp-for="@Model.TamanhosNum" type="text" class="form-control" placeholder="Utilize ; como separador" wrap="soft" style="height: 125px;"></textarea>
                <label class="col-form-label" for="TamanhosNum">@localizer["Tamanhos numéricos"]</label>
                <small><span asp-validation-for="@Model.TamanhosNum" class="text-danger"></span></small>
            </div>
        </div>
    </div>

    <br/>

    <div class="form-group justify-content-between" style="margin-bottom: 0px !important">
        @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Edit)).Result.Succeeded)
        {
            <button type="submit" class="btn btn-success">@localizer["Salvar"]</button>
        }
        <button type="button" class="btn btn-secondary close-button" data-bs-dismiss="modal">@localizer["Cancelar"]</button>
    </div>
</form>


<!-- jquery-validation translated messages -->
@{
    string messageFile = @localizer["messages_pt.js"].Value;
    string url = "/lib/jquery-validation/" + messageFile;
}
<script type="text/javascript" src=@url></script>


<script type="text/javascript" language=javascript>

    $("#create-form").removeData("validator");

    $("#create-form").validate({
        rules: {
            Nome: {
                required: true
            },
            TamanhosAlf: {
                required: true
            },
            TamanhosNum: {
                required: true
            }
        },
        errorElement: "div",
        errorPlacement: function (error, element) {
            error.addClass("invalid-feedback");
            error.insertAfter(element);
        },
        highlight: function (element) {
            $(element).removeClass('is-valid').addClass('is-invalid');
        },
        unhighlight: function (element) {
            $(element).removeClass('is-invalid').addClass('is-valid');
        }
    });

</script>

LVLgroupApp/Areas/Artigo/Views/Gender/_ViewAll.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@using Core.Constants
@using LVLgroupApp.Areas.Artigo.Models.Gender
@model IEnumerable<GenderViewModel>

<style>
    table.dataTable thead th {
        vertical-align: middle !important;
    }
</style>

<table id="genderTable" class="table table-striped table-bordered dt-responsive display hover" width="100%" cellspacing="0">
    <thead> 
        <tr>
            <th>@localizer["Id"]</th>
            <th>@localizer["Nome"]</th>
            <th>@localizer["Tamanhos numéricos"]</th>
            <th>@localizer["Tamanhos alfanuméricos"]</th>
            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Delete)).Result.Succeeded
               || (AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Edit)).Result.Succeeded)
            {
                <th>@localizer["Ações"]</th>
            }
        </tr>
    </thead>
    <tbody>

        @foreach (var gender in Model)
        {
        <tr>
            <td>
                @gender.Id
            </td>
            <td>
                @gender.Nome
            </td>
            <td>
                @gender.TamanhosNum
            </td>
            <td>
                @gender.TamanhosAlf
            </td>
            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Delete)).Result.Succeeded
                ||    (AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Edit)).Result.Succeeded)
            {
                <td text-right">
                        <div class="btn-group dropend">
                            <button id="dropdown_@gender.Id" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @localizer["Ação"]
                            </button>
                            <ul class="dropdown-menu dropdown-menu-table shadow animated--grow-in" aria-labelledby="dropdown_@gender.Id">
                            <li>
                                @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Edit)).Result.Succeeded)
                                {
                                    <a onclick="jQueryModalGet('/artigo/gender/OnGetCreateOrEdit?id=@gender.Id','@localizer["Editar género"]', event, 'modal-xl')" class="dropdown-item"><i class="fas fa-pencil-alt"></i>  @localizer["Editar"]</a>
                                }
                            </li>
                            <li>
                                @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Genders.Delete)).Result.Succeeded)
                                {
                                    <form id="form_delete_@gender.Id" asp-area="Artigo" asp-controller="Gender" method="post" asp-action="OnPostDelete" asp-route-id="@gender.Id" onsubmit="return jQueryModalDelete(this, event, '@localizer["Tem a certeza que pretende remover este género?"]')">
                                        <a href="javascript:$('#form_delete_@gender.Id').submit();" class="dropdown-item"><i class="fas fa-trash-alt"></i>  @localizer["Remover"]</a>
                                    </form>
                                }
                            </li>
                        </ul>
                    </div>
                </td>
            }
        </tr>
        }
    </tbody>
</table>


<script>

    $(document).ready(function () {

        var logo = getLVLlogo('logo-lvl-dark.png');

        var options = {
            isEnabled: true,
            saveState: false
        };

        var languagePath = '@Url.Content("~/lib/datatables/localizer/")';
        var languageFile = '@localizer["Portuguese.json"]';
        var _language = languagePath + languageFile;

        var table = $("#genderTable").DataTable({
            dom: "<'row'<'col-sm-12 col-md-4'B><'col-sm-12 col-md-4 mt-1'l><'col-sm-12 col-md-4 mt-1'f>>" +
                "<'row'<'col-sm-12't>>" +
                "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7 mt-3'p>>",
            stateSave: true,
            //scrollX: true,
            //scrollY: true,
            responsive: false,
            fixedHeader: {
                header: true,
                headerOffset: $('#navigationBar').height()
            },
            language: {
                url: _language
            },
            lengthMenu: [
                [20, 50, 100, 500, 1000, -1],
                [20, 50, 100, 500, 1000, '@localizer["Todos"]'],
            ],
            buttons: [
                {
                    extend: 'copy',
                    text: '<i class="fas fa-copy"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de tamanhos por género"]'
                },
                {
                    extend: 'pdf',
                    text: '<i class="fas fa-file-pdf"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de tamanhos por género"]',
                    customize: function (doc) {
                        doc.content.splice(1, 0, {
                            margin: [0, 0, 0, 12],
                            alignment: 'center',
                            image: 'data: image/*;base64,' + logo,
                            fit: [100, 100]
                        });
                    }
                },
                {
                    extend: 'excel',
                    text: '<i class="fas fa-file-excel"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de tamanhos por género"]'
                },
                {
                    extend: 'print',
                    text: '<i class="fas fa-print"></i>',
                    orientation: 'landscape',
                    exportOptions: {
                        columns: ':visible'
                    },
                    title: '@localizer["Lista de tamanhos por género"]'
                },
                {
                    extend: 'colvis',
                    text: '<i class="fas fa-eye-slash"></i>',
                }
            ],
            order: [[0, "desc"]],
            columnDefs: [
                { visible: false, targets: [0] }
            ]
        });

        $('#genderTable').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
            $('.dataTables_scrollHead').addClass('dropdown-visible');
        })
        .on('hide.bs.dropdown', function () {
            $('.dataTables_scrollBody').removeClass('dropdown-visible');
            $('.dataTables_scrollHead').removeClass('dropdown-visible');
        });

        $('#genderTable tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            } else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });

        $('#genderTable tbody').on('dblclick', 'tr', function () {
            $(this).addClass('selected');
            var data = table.row(this).data();
            //alert('You clicked on ' + data[0] + '\'s row');
            jQueryModalGet('/artigo/gender/OnGetCreateOrEdit?id=' + data[0], '@localizer["Editar género"]', event, 'modal-xl')
        });

        function getLVLlogo(logoName) {

            let _logoName = logoName;
            let _url = "/Claim/Foto/GetLVLlogo?logoName=_logoName";
            let formData = new FormData();
            formData.append("logoName", _logoName);

            $.ajax(
                {
                    type: "POST",
                    url: _url,
                    processData: false,
                    contentType: false,
                    data: formData,
                    dataType: 'json',
                    success: function (data) {
                        if (data.status == "success") {
                            logo = data.logoBase64;
                            //alert(logo);
                        }
                    },
                    error: function () {
                        alert("getLVLlogo: Error occurs");
                    }
                }
            );

        };

    });
</script>